// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owlnuyqzhqpwvlkwsuep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bG51eXF6aHFwd3Zsa3dzdWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTk4MjksImV4cCI6MjA2NTYzNTgyOX0.ME9SHLRz0oFpC9GuBCdlUaZPJFEdS67j4rPpDZEarGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);